Matdungsan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pageapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('mountains.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('loginInfo/', views.loginInfo, name="loginInfo"),
    path('myCompletedMT/', views.myCompletedMT, name="myCompletedMT"),
]

mountains/urls.py
from django.urls import path
from . import views

app_name = 'mountains'

urlpatterns = [
    path("addMountain/", views.addMountain, name="addMountain"),
    path('completeClimbing/', views.completeClimbing, name="completeClimbing"),
    path('searchingResult/', views.searchingResult, name="searchingResult"),
    path('completeMT/', views.completeMT, name="completeMT"),
]

pageapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('createPost/', views.createPost, name='createPost'),
    path('readPost/', views.readPost, name='readPost'),
    path('searchPost/', views.searchPost, name='searchPost'),
    path('deletePost/<int:post_id>', views.deletePost, name='deletePost'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, blank=False)
    age_group = models.IntegerField(blank=False)
    complete_count = models.IntegerField(blank=False)
    grade = models.CharField(max_length=10, blank=False)

mountains/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Mountain(models.Model):
    name = models.CharField(max_length=20)
    address = models.TextField()

# 완등한 산의 id를 저장하는 모델
class CompletedMT(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, db_column="user_id")
    mountain_id = models.ForeignKey(Mountain, on_delete=models.CASCADE, db_column="mountain_id")
    mountain_name = models.CharField(max_length=20)

pageapp/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.TextField(default="(제목 없음)", blank=False)
    image = models.ImageField(blank=True, upload_to="images/")
    content = models.TextField(blank=True)
    username = models.CharField(max_length=20)

accounts/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import HttpResponseRedirect
from .models import *
from mountains.models import CompletedMT

# Create your views here.
def login(request):
    if request.method == "POST":
        username = request.POST['user_name']
        password = request.POST['user_password']
        user = auth.authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            auth.login(request, user)
            return redirect('index')
        else:
            return render(request, 'login.html',
            {'error': '아이디 또는 비밀번호가 일치하지 않습니다.'})
    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('index')


def signup(request):
    if request.method == 'POST':
        if request.POST['user_password1'] == request.POST['user_password2']:
            user = User.objects.create_user(
                username=request.POST['user_name'], password=request.POST['user_password1'],
                email=request.POST['user_email']
            )
            gender = request.POST['gender']
            age_group = request.POST['age_group']
            complete_count = request.POST['complete_count']
            grade = request.POST['grade']
            profile = Profile(user=user, gender=gender, age_group=age_group, complete_count=complete_count, grade=grade)
            profile.save()

            auth.login(request, user)
            return redirect('index')
        return render(request, 'signup.html')
    return render(request, 'signup.html')

def loginInfo(request):
    return render(request, "loginInfo.html")


# 객체가 iterable인지 확인하는 함수임
def isiterable(p_object):
    try:
        it = iter(p_object)
    except TypeError:
        return False
    return True


def myCompletedMT(request):
    user_id = request.POST['user_id']
    myCompletedMT = CompletedMT.objects.filter(user_id=user_id)
    is_iterable = isiterable(myCompletedMT)
    return render(request, "myCompletedMT.html", {'mountains' : myCompletedMT, 'is_iterable':is_iterable})

mountains/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import User
from accounts.models import Profile

# Create your views here.

def addMountain(request):
    if request.method == "POST":
        mt_name = request.POST['mountain_name']
        mt_address = request.POST['mountain_address']
        mountain = Mountain(name=mt_name, address=mt_address)
        mountain.save()
        return redirect('index')
    return render(request, "addMountain.html")


def completeClimbing(request):
    user_id = request.POST["user_id"]
    mountains = Mountain.objects.all()

    # 이미 완등했던 산의 정보를 불러와서 산의 id값 정보를 html로 넘긴다.
    completed_mt = CompletedMT.objects.filter(user_id=user_id)
    completed_mt_id = []
    for com_mt in completed_mt:
        print(com_mt.mountain_id.id)
        completed_mt_id.append(com_mt.mountain_id.id)
    return render(request, 'completeClimbing.html', {'mountains':mountains, 'completed_mt_id':completed_mt_id})
    

def searchingResult(request):
    input = request.GET['search']
    splited_str = input.split() # 검색창에 입력한 문자열을 공백을 기준으로 나눔
    san_str = "" # '산'이 들어간 문자열 저장할 곳
    for x in splited_str:
        if '산' in x:
            san_str = x
    mountain = Mountain.objects.get(name=san_str)
    return render(request, 'searchingResult.html', {'mountain':mountain})

def completeMT(request):
    user_id = int(request.POST['user_id'])
    mt_id = int(request.POST['mt_id'])
    mt_name = request.POST['mt_name']
    
    user = get_object_or_404(User, pk=user_id)
    mt = get_object_or_404(Mountain, pk=mt_id)

    com_mt = CompletedMT() # 완등한 산을 저장하는 모델
    com_mt.user_id = user
    com_mt.mountain_id = mt
    com_mt.mountain_name = mt_name
    com_mt.save()
    user.profile.complete_count += 1
    if user.profile.complete_count >= 10:
        user.profile.grade = "프로산악인"
    elif user.profile.complete_count >= 5:
        user.profile.grade = "등산매니아"
    else:
        pass
    user.profile.save()    
    return redirect('index')

pageapp/views.py
from django.shortcuts import render
from .models import *
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import User
# Create your views here.

def index(request):
    posts = Post.objects.all()
    post_content = {'posts' : posts}
    return render(request, 'index.html', post_content)

def createPost(request):
    if request.method == "POST":
        title = request.POST["title"]
        image = request.FILES['image']
        content = request.POST['content']
        username = request.POST['username']
        new_post = Post(title=title, image=image, content=content, username=username)
        new_post.save()
        print("정상적으로 저장 완료!")
        return redirect('readPost')
    return render(request, 'createPost.html')

def readPost(request):
    posts = Post.objects.all()
    post_content = {'posts' : posts}
    return render(request, 'readPost.html', post_content)

def searchPost(request):
    input_text = request.GET['search']
    posts = Post.objects.all()
    search_result = []
    for post in posts:
        if input_text in post.title:
            search_result.append(post)    
    results = {'results' : search_result}
    return render(request, 'searchPost.html', results)

def deletePost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('readPost')

accounts/templates/login.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 로그인</title>
</head>

<body>
    <h2>맛등산 로그인</h2>
    <form action="{% url 'accounts:login' %}" method="POST" autocomplete="off">
        {% csrf_token %}
        <fieldset>
            <legend>로그인 하기</legend>

            <ul>
                <li><label>아이디 <input type="text" name="user_name" size="10"></label></li>
                <li><label>비밀번호 <input type="password" name="user_password" size="10"></label></li>
                <li><input type="submit" value="로그인"></li>
            </ul>

        </fieldset>
    </form>
    <p>{{error}}</p>
</body>

</html>

accounts/templates/loginInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>
        아이디: {{ user.username }}<br>
        이메일: {{ user.email }}<br>
        성별: {{ user.profile.gender }}<br>
        완등 횟수: {{ user.profile.complete_count }}<br>
        등급: {{ user.profile.grade }}<br>
    </p>
    <form method="POST" action="{% url 'accounts:myCompletedMT' %}">
        {% csrf_token %}
        <input type="hidden" value="{{ user.id }}" name="user_id">
        <input type="submit" value="완등한 산 보기">
    </form>
    
</body>
</html>

accounts/templates/myCompletedMT.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 :: 완등한 산 보기</title>
</head>
<body>
    <h1>{{ user.username }} 님이 완등한 산은?</h1>
    <fieldset>
        <legend><h2>내가 완등한 산은...</h2></legend>
        {% if is_iterable %}
            {% for mt in mountains %}
                <p>{{ mt.mountain_name }}</p>
            {% endfor %}
        {% else %}
            <p>{{ mountains.mountain_name }}</p>
        {% endif %}
    </fieldset>
    
</body>
</html>

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 회원가입</title>
</head>

<body>
    <h2>맛등산 회원가입</h2>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>필수 정보 입력</legend>
            <ul>
                <li>
                    <label>아이디 <input type="text" name="user_name" size="10" maxlength="20"></label>
                </li>
                <li>
                    <label>비밀번호 <input type="password" name="user_password1" size="10"></label>
                </li>
                <li>
                    <label>비밀번호 확인 <input type="password" name="user_password2" size="10"></label>
                </li>
                <li>
                    <label>이메일 <input type="email" name="user_email" size="20"></label>
                </li>
                <li>
                    <label>성별</label>
                    <br>
                    <label><input type="radio" name="gender" value="남자">남자</label>
                    <label><input type="radio" name="gender" value="여자">여자</label>
                </li>
                <li>
                    <label>연령대</label>
                    <br>
                    <label><input type="radio" name="age_group" value="10">10대 이하 </label>
                    <label><input type="radio" name="age_group" value="20">20대 </label>
                    <label><input type="radio" name="age_group" value="30">30대 </label>
                    <label><input type="radio" name="age_group" value="40">40대 </label>
                    <label><input type="radio" name="age_group" value="50">50대 이상</label>
                </li>
            </ul>
            <input type="hidden" name="complete_count" value="0">
            <input type="hidden" name="grade" value="등린이">
            
            <input type="submit" value="회원가입">
            <input type="reset" value="다시 입력">
        </fieldset>
    </form>

</body>

</html>

mountains/templates/addMountain.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 산 정보 추가</title>
</head>
<body>
    <fieldset>
        <legend>산 정보 추가하기</legend>
        <form method="POST" action="{% url 'mountains:addMountain' %}">
            {% csrf_token %}
            <ul>
                <li>
                    <label>산 이름: <input type="text" name="mountain_name" placeholder="산 이름을 입력해주세요."></label>
                </li>
                <li>
                    <br>
                    <label>주소: <textarea name="mountain_address" placeholder="산 주소를 입력해주세요"></textarea></label>
                </li>
            </ul>
            <input type="submit" value="완료">
        </form>
    </fieldset>
    
</body>
</html>

mountains/templates/completeClimbing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 :: 완등하는 사이트</title>
</head>
<body>
    <h2>완등 페이지</h2>

    <form method="GET" action="{% url 'mountains:searchingResult' %}">
        <fieldset>
            <legend>산 검색</legend>
            <input type="search" name="search">
            <input type="submit" value="검색">
        </fieldset>
    </form>

    <h2>산 리스트</h2>
    {% for mt in mountains %}
        <fieldset>
            <legend><h4>{{ mt.name }}</h4></legend>
            <p>{{ mt.address }}</p>
            {% if mt.id not in completed_mt_id  %}
                <form method="POST" action="{% url 'mountains:completeMT' %}">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="mt_id" value="{{ mt.id }}">
                    <input type="hidden" name="mt_name" value="{{ mt.name }}">
                    <input type="submit" value="완등">
                </form>
            {% else %}
                <p>완등 완료</p>
            {% endif %}
        </fieldset>
    {% endfor %}
    
</body>
</html>

mountains/templates/searchingResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>산 검색결과</title>
</head>
<body>
    <h2>산 검색결과 페이지</h2>

    <form method="GET" action="#">
        {% csrf_token %}
        <fieldset>
            <legend>산 검색</legend>
            <input type="search" name="search">
            <input type="submit" value="검색">
        </fieldset>
    </form>

    <h2>검색결과</h2>
    <fieldset>
        <legend><h4>{{ mountain.name }}</h4></legend>
        <p> {{ mountain.address }}</p>
        <a href="#">
            <button>완등</button>
        </a>
    </fieldset>
    
</body>
</html>

pageapp/templates/createPost.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 후기글 작성</title>
</head>

<body>
    <h2>맛동산 후기글 작성</h2>
    <form action="{% url 'createPost' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend>내용 입력</legend>
            <li>
                <label>제목<br><input type="text" name="title"><br><br></label>
            </li>
            <li>
                <label>이미지<br><input type="file" name="image" accept=".gif, .jpg, .png"><br><br></label>
            </li>
            <li>
                <label>내용<br><textarea name="content"></textarea></label>
            </li>
            <li>
                <input type="hidden" name="username" value="{{ user.username }}">
            </li>
            <li>
                <input type="submit" value="작성완료">
            </li>
        </fieldset>
    </form>
</body>

</html>

pageapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 메인 페이지</title>
</head>
<body>
    <h2>맛등산 메인 페이지</h2>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}">로그아웃</a><br>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인 하기</a><br>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    
    
    <br><br><br>
    <h2>로그인 정보</h2>
    {% if user.is_authenticated %}
        <p>환영합니다, {{ user.username }}님! (로그인 완료)</p>
        <a href="{% url 'accounts:loginInfo' %}">로그인 정보 조회</a>
        
        {% if user.username == "admin" %}
            <a href="{% url 'mountains:addMountain' %}">
                <button>산 추가하기</button>
            </a>
        {% endif %}

        {% if user.profile.grade == "등린이" %}
            <p>완등 뱃지: <img src="{% static 'images/level01.png' %}" width="35"> 등린이</p>
        {% elif user.profile.grade == "등산매니아" %}
            <p>완등 뱃지: <img src="{% static 'images/level02.png' %}" width="35"> 등산매니아</p>
        {% elif user.profile.grade == "프로산악인" %}
            <p>완등 뱃지: <img src="{% static 'images/level03.png' %}" width="35"> 프로산악인</p>
        {% else%}
        {% endif %}
        
    {% else %}
        <p>어서오세요, 먼저 로그인을 해주세요~</p>
    {% endif %}

    

    <h2>완등하러 가기</h2>
    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'mountains:completeClimbing' %}">
            {% csrf_token %}
            <input type=hidden value="{{ user.id }}" name="user_id">
            <input type="submit" value="완등하러 가기">
        </form>
    {% else %}
        <p>먼저 로그인을 해주세요~</p>
    {% endif%}


    <br><br><br>
    <h2>글쓰기 기능</h2>
    {% if user.is_authenticated %}
        <a href="{% url 'createPost' %}">글쓰기</a>
    {% else %}
        <p>로그인을 해야 글을 쓸 수 있습니다.</p>
    {% endif %}

    <br><br><br>
    <h2>후기글 보기</h2>
    
    {% if user.is_authenticated %}
        <a href="{% url 'readPost' %}">후기글 보러가기</a>
    {% else %}
        <p>로그인을 해야 후기글을 볼 수 있습니다.</p>
    {% endif %}


</body>
</html>

pageapp/templates/login.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 로그인</title>
</head>

<body>
    <h2>맛등산 로그인</h2>
    <form action="" method="POST" autocomplete="off"></form>
    <fieldset>
        <legend>로그인 하기</legend>

        <ul>
            <li><label>아이디 <input type="text" id="user_id" size="10"></label></li>
            <li><label>비밀번호 <input type="password" id="user_password" size="10"></label></li>
            <li><input type="submit" value="로그인"></li>
        </ul>

    </fieldset>
    </form>
</body>

</html>

pageapp/templates/readPost.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛동산 후기글 읽기</title>
</head>
<body>
    <a href="{% url 'index' %}">메인 화면으로 가기</a>
    <br><br>

    {% if user.is_authenticated %}
        <form action="{% url 'searchPost' %}" method="GET" autocomplete="on">
            <fieldset>
                <legend>게시글 검색</legend>
                <input type="search" name="search" width="10">
                <input type="submit" value="검색하기">
            </fieldset>
        </form>

        <h2>전체 후기글</h2>
        
        {% for post in posts %}
            <fieldset>
                <legend><strong>{{ post.title }}</strong></legend>
                {% if post.username == user.username %}
                    <a href="#">수정</a>
                    <a href="{% url 'deletePost' post.id %}">삭제</a>
                {% endif %}
                <p>작성자: {{ post.username }}</p>
                <img src="{{ post.image.url }}" alt="후기 사진">
                <p>{{ post.content }}</p>
            </fieldset>
        {% endfor %}            
        

    {% else %}
        <h3>로그인을 하지 않고 들어오셨군요!<br>
        먼저 로그인을 하고 시도해주세요!</h3>
    {% endif %}

    
    
</body>
</html>

pageapp/templates/register.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 회원가입</title>
</head>

<body>
    <h2>맛등산 회원가입</h2>
    <form action="" method="POST">
        <fieldset>
            <legend>필수 정보 입력</legend>
            <ul>
                <li>
                    <label>이름 <input type="text" id="user_name" size="10"></label>
                </li>
                <li>
                    <label>아이디 <input type="text" id="user_id" size="10"></label>
                </li>
                <li>
                    <label>비밀번호 <input type="password" id="user_password" size="10"></label>
                </li>
                <li>
                    <label>이메일 <input type="email" id="user_email" size="20"></label>
                </li>
            </ul>
            <input type="submit" value="회원가입">
            <input type="reset" value="다시 입력">
        </fieldset>
    </form>

</body>

</html>

pageapp/templates/searchPost.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛동산 검색 페이지</title>
</head>
<body>
    <h1>맛동산 검색 결과 페이지!!</h1>
    <a href="{% url 'index' %}">메인 화면으로 가기</a>
    <br><br>

    {% if user.is_authenticated %}
        <form action="{% url 'searchPost' %}" method="GET" autocomplete="on">
            <fieldset>
                <legend><em>게시글 검색</em></legend>
                <input type="search" name="search" width="10">
                <input type="submit" value="검색하기">
            </fieldset>
        </form>
        
        <h2>검색 결과</h2>
        {% for post in results %}
        <fieldset>
            <legend><strong>{{ post.title }}</strong></legend>
                {% if post.username == user.username %}
                    <a href="#">수정</a>
                    <a href="{% url 'deletePost' post.id %}">삭제</a>
                {% endif %}
            <p>작성자: {{ post.username }}</p>
            <img src="{{ post.image.url }}" alt="후기 사진">
            <p>{{ post.content }}</p>
        </fieldset>
        {% endfor %}
    {% else %}
        <h2>로그인 후 이용해주세요.</h2>
    {% endif %}

    
</body>
</html>

pageapp/templates/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>맛등산 회원가입</title>
</head>

<body>
    <h2>맛등산 회원가입</h2>
    <form action="" method="POST">
        <fieldset>
            <legend>필수 정보 입력</legend>
            <ul>
                <li>
                    <label>이름 <input type="text" id="user_name" size="10"></label>
                </li>
                <li>
                    <label>아이디 <input type="text" id="user_id" size="10"></label>
                </li>
                <li>
                    <label>비밀번호 <input type="password" id="user_password" size="10"></label>
                </li>
                <li>
                    <label>이메일 <input type="email" id="user_email" size="20"></label>
                </li>
            </ul>
            <input type="submit" value="회원가입">
            <input type="reset" value="다시 입력">
        </fieldset>
    </form>

</body>

</html>